
import fs from 'fs';
import { join } from 'path';
import PDFDocument from 'pdfkit';
import nodemailer from 'nodemailer';

export function generateCoverLetter(language: string, job: string, about: string) {
  return `Cover letter in ${language}\n\nPosition: ${job}\n\nAbout you: ${about}\n\nGenerated by AI.`;
}

export function generatePDF(content: string, filename: string) {
  const doc = new PDFDocument();
  const filepath = join('/mnt/data', filename);
  const stream = fs.createWriteStream(filepath);
  doc.pipe(stream);
  doc.fontSize(12).text(content);
  doc.end();
  return filepath;
}

export async function sendEmail(to: string, subject: string, text: string, attachmentPath: string) {
  const transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: {
      user: process.env.EMAIL_USER,
      pass: process.env.EMAIL_PASS,
    },
  });

  await transporter.sendMail({
    from: process.env.EMAIL_USER,
    to,
    subject,
    text,
    attachments: [{ path: attachmentPath }],
  });
}
